### ISSUE TITLE
Disable CI triggers

### ISSUE THREAD

**Issue by ss2165** [CQCL/pytemplate#42]
The example workflow file (`python-app.yml`) is nice to have but it does a lot of non-trivial things on every push to main, which someone just starting out with the template might be surprised by. It might be worth commenting out the triggers, or making the triggers somehow specific to this template repository.

**Comment by NathanCQC** [comment]
I agree with this.

**Comment by qartik** [comment]
I am open to all these ideas. Perhaps just a note in the README to pick and choose which actions/triggers to keep might be sufficient?

**Comment by ss2165** [comment]
A prominent note in the readme is a good idea regardless. Maybe keep the PR trigger and comment out on push to main?
